### ISSUE TITLE
Creating a mobile interface for users to enter their school numbers and implementing a request sending feature to send this information to a local web server.

### ISSUE THREAD

**Issue by BurakDmb** [ETU-ABC/ABC-Mirror#12]
For ABC-EtuCourseTimetable module to work properly for users, we need to get their school number from our mobile application and sending this info to our local mirror web server.

In this issue, we need to create a form page(or a similar page) in our mobile app to get the users school number.

After that, we need to send this information to our local mirrors web server through a http get request. We only need to implement the request sending feature implementation in this issue. 
The job of processing requests in the web server is another issue and will be implemented parallel with this issue.

**Comment by AlperenElbasan** [comment]
Done! (except that server side is not ready yet).
